[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dlsia"
version = "0.3.2"
description = "Deep Learning for Scientific Image Analysis"
authors = [
    { name: "Petrus Hendrik Zwart", email: "PHZwart@lbl.gov" },
    { name: "Eric J. Roberts", email: "EJroberts@lbl.gov" },
]
dependencies = [
    "torch>=1.11",
    "torchvision>=0.13",
    "numpy>=1.23",
    "scipy>=1.8",
    "scikit-learn>=0.24",
    "scikit-image>=0.18",
    "pandas>=1.2",
    "networkx>=3.0",
    "h5py>=3.1",
    "plotly>=5.3",
    "dill>=0.3",
    "einops>=0.3",
    "umap-learn>=0.5",
    "kaleido>=0.2",
    "zarr>=2.11",
    "torchmetrics>=0.11",
    "pytorch-lightning>=2.0",
    "sphinx>=7.2",
    "nbsphinx>=0.8",
    "sphinx-rtd-theme>=1.0",
]